DROP TABLE IF EXISTS characteristics CASCADE;

CREATE TABLE IF NOT EXISTS characteristics (
  id              int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  product_id      int references products(id),
  name text
);

CREATE index product_id_idx on characteristics(product_id);

COPY characteristics
FROM '/Users/arpanshrestha/Desktop/HackReactor/SDC/r_service/data/characteristics.csv'
WITH (FORMAT csv, HEADER true, DELIMITER ',');