DROP TABLE IF EXISTS characteristic_reviews CASCADE;

CREATE TABLE IF NOT EXISTS characteristic_reviews (
  id                int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  characteristic_id int references characteristics(id),
  review_id         int references reviews(id),
  value             int
);

CREATE index characteristic_id_idx on reviews(characteristic_id);
CREATE index review_id_idx on reviews(review_id);

COPY characteristic_reviews
FROM '/Users/arpanshrestha/Desktop/HackReactor/SDC/r_service/data/characteristic_reviews.csv'
WITH (FORMAT csv, HEADER true, DELIMITER ',');
