DROP TABLE IF EXISTS products CASCADE;

CREATE TABLE IF NOT EXISTS products (
  id            int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name          text,
  slogan        text,
  description   text,
  category      text,
  default_price int 
);

COPY products
FROM '/Users/arpanshrestha/Desktop/HackReactor/SDC/r_service/data/product.csv'
WITH (FORMAT csv, HEADER true, DELIMITER ',');









