DROP TABLE IF EXISTS reviews_photos CASCADE;

CREATE TABLE IF NOT EXISTS reviews_photos (
  id              int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  review_id       int references reviews(id),
  url             text
);

CREATE index review_id_idx on reviews_photos(review_id);

COPY reviews_photos
FROM '/Users/arpanshrestha/Desktop/HackReactor/SDC/r_service/data/reviews_photos.csv'
WITH (FORMAT csv, HEADER true, DELIMITER ',');