DROP TABLE IF EXISTS reviews CASCADE;

CREATE TABLE IF NOT EXISTS reviews (
  id              int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  product_id      int references products(id),
  rating          int,
  date            text,
  summary         text,
  body            text,
  recommend       boolean,
  reported        boolean,
  reviewer_name   text,
  reviewer_email  text,
  response        text,
  helpfulness     int
);

CREATE index product_id_idx on reviews(product_id);

COPY reviews
FROM '/Users/arpanshrestha/Desktop/HackReactor/SDC/r_service/data/cleanReview.csv'
WITH (FORMAT csv, HEADER true, DELIMITER ',');