DROP TABLE IF EXISTS products, reviews, reviews_photos, characteristics, characteristic_reviews CASCADE;

CREATE TABLE IF NOT EXISTS products (
  id            int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name          text,
  slogan        text,
  description   text,
  category      text,
  default_price int 
);

COPY products(id)
FROM '../../data/product.csv'
WITH (FORMAT csv, HEADER true)

CREATE TABLE IF NOT EXISTS reviews (
  id              int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  product_id      int references products(id),
  rating          int,
  date            date,
  summary         text,
  body            text,
  recommend       boolean,
  reported        boolean,
  reviewer_name   text,
  reviewer_email  text,
  response        text,
  helpfulness     int
);

COPY reviews
FROM '../../data/reviews.csv'
WITH (FORMAT csv, HEADER true);

CREATE TABLE IF NOT EXISTS reviews_photos (
  id              int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  review_id       int references reviews(id),
  url             text
);

COPY photos
FROM '../../data/reviews_photos.csv'
WITH (FORMAT csv, HEADER true);

CREATE TABLE IF NOT EXISTS characteristics (
  id              int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  product_id      int references products(id),
  name text
);

COPY characteristics
FROM '../../data/characteristics.csv'
WITH (FORMAT csv, HEADER true);

CREATE TABLE IF NOT EXISTS characteristic_reviews (
  id                int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  characteristic_id int references characteristics(id),
  review_id         int references reviews(id),
  value             int
);

COPY characteristic_reviews
FROM '../../data/characteristics_reviews.csv'
WITH (FORMAT csv, HEADER true);


