\c testdb;

DROP TABLE IF EXISTS products, reviews, reviews_photos, characteristics, characteristic_reviews CASCADE;

CREATE TABLE IF NOT EXISTS products (
  id            int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name          text,
  slogan        text,
  description   text,
  category      text,
  default_price int
);

COPY products
FROM '/Users/arpanshrestha/Desktop/HackReactor/SDC/r_service/data/product.csv'
WITH (FORMAT csv, HEADER true, DELIMITER ',');

CREATE TABLE IF NOT EXISTS reviews (
  id              int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  product_id      int references products(id),
  rating          int,
  date            text,
  summary         text,
  body            text,
  recommend       boolean,
  reported        boolean,
  reviewer_name   text,
  reviewer_email  text,
  response        text,
  helpfulness     int
);
CREATE index product_id_idx on reviews(product_id);
COPY reviews
FROM '/Users/arpanshrestha/Desktop/HackReactor/SDC/r_service/data/cleanReview.csv'
WITH (FORMAT csv, HEADER true, DELIMITER ',');

CREATE TABLE IF NOT EXISTS reviews_photos (
  id              int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  review_id       int references reviews(id),
  url             text
);
CREATE index review_id_idx on reviews_photos(review_id);
COPY reviews_photos
FROM '/Users/arpanshrestha/Desktop/HackReactor/SDC/r_service/data/reviews_photos.csv'
WITH (FORMAT csv, HEADER true, DELIMITER ',');

CREATE TABLE IF NOT EXISTS characteristics (
  id              int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  product_id      int references products(id),
  name text
);
CREATE index charProduct_id_idx on characteristics(product_id);
COPY characteristics
FROM '/Users/arpanshrestha/Desktop/HackReactor/SDC/r_service/data/characteristics.csv'
WITH (FORMAT csv, HEADER true, DELIMITER ',');

CREATE TABLE IF NOT EXISTS characteristic_reviews (
  id                int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  characteristic_id int references characteristics(id),
  review_id         int references reviews(id),
  value             int
);
CREATE index char_idx on characteristic_reviews(characteristic_id, review_id);
COPY characteristic_reviews
FROM '/Users/arpanshrestha/Desktop/HackReactor/SDC/r_service/data/characteristic_reviews.csv'
WITH (FORMAT csv, HEADER true, DELIMITER ',');